Martijn
mwheymans/bookmi pull request #9
Opened 2018-10-19 14:51 UTC by mwheymans

Changed files so that pdf version of book can be made.  Made also adaptations in Chapter 4 and 6, not in text but only in fig and table nrs.  Made most text changes to Chapter 3.

2018-10-29 13:54 UTC, child-health-statistics requested changes

2018-10-29 13:54 UTC, child-health-statistics commented on 03-SingleMissingdataimputation.Rmd
> +You can aplly regression imputation in R with as method “norm.predict” in the mice function. The Pain variable is used to predict the missing values in the Tampa scale variable.
apply in de eerste regel.

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +Yoy do regression imputation in SPSS via the Missing Value Analysis procedures. There are two options for regression imputation, the Regression option and the EM (Expectation Maximization) option. Th
De eerste zin zou ik hier anders formuleren: 
Regression imputation in SPSS can be performed via the Missing Value Analysis procedure.

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +Yoy do regression imputation in SPSS via the Missing Value Analysis procedures. There are two options for regression imputation, the Regression option and the EM (Expectation Maximization) option. Th
De eerste zin zou ik hier anders formuleren: 
Regression imputation in SPSS can be performed via the Missing Value Analysis procedure.

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +Click on Continue -> EM and Choose for Normal in the Distribution group. Than thick Save completed data and give the dataset a name, for example “ImpTampa_EM” (Figure \@ref(fig:fig3-12)).
> Continue -> EM
Select Normal in the Distribution grop and Save completed data ...

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +Click Continue -> OK. The new dataset “ImpTampa_EM” will open in a new window in SPSS. In this dataset the imputed data of the Tampascale Variable together with the original data is stored (Figure \@
> Continue -> OK

The new dataset....

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +We now compare the EM procedure with a two-step linear regression procedure. We first estimate the relationship between Pain and the Tampa scale variable in the dataset with linear regression after w
We **can** compare the EM procedure with a..

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +Now impute the missing values in the Tampa scale variable and compare them with the EM estimates. You see that the results are the same.
When the missing values in the Tampa scale variable are imputed and compared with the EM estimates, the results are the same.

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +You can aplly regression imputation in R with as method “norm.predict” in the mice function. The Pain variable is used to predict the missing values in the Tampa scale variable.
Regression imputation in R can be **applied** with as...

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +With Stochastic regression models imputation uncertainty is accounted for by adding extra error variance to the predicted values that are generated by the linear regression model. Stochastic regressi
With Stochastic regression models imputation, uncertainty is accounted for by adding extra error variance to the predicted values that are generated by the linear regression model. Stochastic regression can be performed in SPSS via the Missing Value Analysis and the Regression Estimation option. However, the Regression Estimation option in SPSS generates incorrect regression coefficient estimates (von Hippel, 2004) and will therefore not further be discussed.

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +With Stochastic regression models imputation uncertainty is accounted for by adding extra error variance to the predicted values that are generated by the linear regression model. Stochastic regressi
Misschien anders formuleren ? Uitleggen hoe je dit kunt doen in SPSS zodat je wel goede schattingen krijgt? Je kunt toch wel random error schatten? En die aan de predicted values van regression imputation toevoegen? Ook misschien zelf nog even testen wat von Hippel zegt.. want hij is niet een super betrouwbare bron!

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +You can apply stochastic regression imputation in R with the mice function. For this you use as method "norm.nob".
You can **perform** stochastic

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +The difference between the non-Bayesian imputation procedure that you applied above and Bayesian imputation is that with the latter method extra variation is added to the imputed values via the regre
The difference between the non-Bayesian imputation procedure that is described above and Bayesian imputation is that with the latter method the extra variation is added via the regression coefficients, indead of directly to the imputed values. The Bayesian idea is that there is not one population regression coefficient, but that the parameter should be drawn from a distribution. The frequentist idea is that there is one true population regression coefficient, which has uncertainty reflected in the confidence interval around it. In this book we mostly built on the frequentist idea. For more information about the theory of Bayesian statistics we refer to the books of Box and Tiao (1992), Enders (2012) and Gelman et al. (2004).

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +The difference between the non-Bayesian imputation procedure that you applied above and Bayesian imputation is that with the latter method extra variation is added to the imputed values via the regre
The difference between the non-Bayesian imputation procedure that is described above and Bayesian imputation is that with the latter method the extra variation is added via the regression coefficients, indead of directly to the imputed values. The Bayesian idea is that there is not one population regression coefficient, but that the parameter should be drawn from a distribution. The frequentist idea is that there is one true population regression coefficient, which has uncertainty reflected in the confidence interval around it. In this book we mostly built on the frequentist idea. For more information about the theory of Bayesian statistics we refer to the books of Box and Tiao (1992), Enders (2012) and Gelman et al. (2004).

2018-10-29 13:56 UTC, iriseekhout commented on 03-SingleMissingdataimputation.Rmd
> +The difference between the non-Bayesian imputation procedure that you applied above and Bayesian imputation is that with the latter method extra variation is added to the imputed values via the regre
Ik vond dit stukje niet zo duidelijk. Heb een poging gedaan tot herschrijven, maar weet niet of het nu al perfect is.

2018-11-05 18:31 UTC, mwheymans commented
Closed

2018-12-07 09:06 UTC, closed without merging